import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms',
  description: 'Terms of service for using Quantara.',
};

export default function TermsPage() {
  return (
    <div className="space-y-5 text-sm leading-relaxed text-fg sm:text-base">
      <header>
        <h1 className="fluid-display-h1 text-fg">
          Terms
        </h1>
        <p className="mt-1 text-xs text-muted">
          Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>
      </header>

      <p className="rounded-card border border-warning/30 bg-warning/10 p-3 text-sm text-warning">
        <strong>Placeholder.</strong> This page needs legal review before launch. Treat the
        contents below as a draft, not legal advice.
      </p>

      <h2 className="font-display text-sm uppercase tracking-display text-muted">
        Using Quantara
      </h2>
      <p>
        By signing in you agree to use the service for personal study and not to attempt to
        disrupt it, scrape content at scale, or use it to train competing models. We may update
        these terms as the product evolves; we&rsquo;ll bump the date above and notify signed-in users
        the next time they load the app.
      </p>

      <h2 className="font-display text-sm uppercase tracking-display text-muted">
        Free tier
      </h2>
      <p>
        Quantara runs on a free tier with rate limits per user. Limits are generous for daily
        study but we may need to tighten them if we see abuse. We never charge the free tier
        without an explicit opt-in.
      </p>

      <h2 className="font-display text-sm uppercase tracking-display text-muted">
        AI output
      </h2>
      <p>
        Quiz prompts, explanations, and chat replies are generated by large language models.
        They are usually accurate but can be confidently wrong. Use them as study aids, not
        authoritative sources. If you spot a mistake, the in-app feedback surface is the fastest
        way to reach us.
      </p>

      <h2 className="font-display text-sm uppercase tracking-display text-muted">
        Intellectual property
      </h2>
      <p>
        The brand, layout, and the MCQ bank are owned by Quantara. The bank contains items that
        were authored by hand for this product; please don&rsquo;t redistribute them.
      </p>

      <h2 className="font-display text-sm uppercase tracking-display text-muted">
        Liability
      </h2>
      <p>
        The service is provided as-is. We&rsquo;re a small team and we&rsquo;ll do our best to keep it up,
        but we can&rsquo;t guarantee 100% uptime or zero data loss. Always export your own notes
        from anything important.
      </p>
    </div>
  );
}