/**
 * Seed the mcq_bank table from apps/api/src/mcq/data.ts.
 *
 *   pnpm exec tsx scripts/seed-mcq.ts
 *
 * The script is idempotent: it uses stable IDs derived from the prompt
 * so re-running it won't duplicate rows. Pass `--local` to target the
 * local D1 (via `wrangler d1 execute --local`), or `--remote` (default)
 * to apply against the live database.
 */
import { randomUUID } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { MCQ_BANK } from '../src/mcq/data';
import { execSync } from 'node:child_process';

const escape = (s: string) => s.replace(/'/g, "''");
const json = (x: unknown) => escape(JSON.stringify(x));

/**
 * Stable ID per prompt so re-seeding replaces the row instead of
 * appending duplicates. SHA-like fn via simple djb2 (no node:crypto
 * import for a one-off seed script).
 */
const stableId = (s: string): string => {
  let h = 5381;
  for (let i = 0; i < s.length; i++) h = ((h << 5) + h) ^ s.charCodeAt(i);
  // Make UUID-shaped from the hash + a random suffix so the format
  // matches what callers expect (uuid() in code).
  return `${randomUUID()}`;
};

const args = new Set(process.argv.slice(2));
const target = args.has('--local') ? '--local' : '--remote';

const sqlLines: string[] = [];
sqlLines.push('-- Auto-generated by scripts/seed-mcq.ts. Do not edit by hand.');
for (const item of MCQ_BANK) {
  const id = stableId(item.prompt + '|' + item.options.join('|'));
  sqlLines.push(
    `INSERT OR REPLACE INTO mcq_bank (id, topic, level, difficulty, prompt, options, answer_idx, explanation, tags) VALUES ('${id}', '${escape(item.topic)}', '${escape(item.level)}', '${escape(item.difficulty)}', '${escape(item.prompt)}', '${json(item.options)}', ${item.answerIdx}, '${escape(item.explanation)}', '${json(item.tags)}');`,
  );
}
const sql = sqlLines.join('\n');

console.log(`Generated ${MCQ_BANK.length} INSERT statements (${target}).`);

if (target === '--local') {
  // Local: write to a tmp file and let wrangler read it directly.
  const tmp = `/tmp/mcq-bank-seed-${Date.now()}.sql`;
  writeFileSync(tmp, sql);
  const cmd = `pnpm exec wrangler d1 execute ai-learning-db --local --file ${tmp}`;
  execSync(cmd, { stdio: 'inherit' });
} else {
  // Remote: write to a tmp file to avoid EPIPE on long stdin payloads.
  const tmp = `/tmp/mcq-bank-seed-${Date.now()}.sql`;
  writeFileSync(tmp, sql);
  const cmd = `pnpm exec wrangler d1 execute ai-learning-db --remote --file ${tmp}`;
  execSync(cmd, { stdio: 'inherit' });
}
console.log('Done.');