/**
 * Curated MCQ bank — 150+ items across A2..C1.
 *
 * Each item is intentionally hand-written so:
 *   - Distractors look plausible (no obvious giveaway like "all of the above"
 *     or repeated single-word options).
 *   - Explanations surface the underlying rule, not just the answer.
 *   - Hard-tier items require the learner to read the WHOLE sentence and
 *     reason about it, not pattern-match on a single keyword.
 *
 * `difficulty: 'easy'` items are the default — they check recognition of the
 * underlying rule. `difficulty: 'hard'` items are served only when the user
 * opts in via the Hard chip on the quiz setup; they require multi-clause
 * reasoning, nuanced collocations, or subtle grammar choices with no
 * pattern-match shortcut.
 *
 * Schema mirrors `mcqBank` in apps/api/src/db/schema.ts. Loaded by the
 * seed script in apps/api/scripts/seed-mcq.ts.
 */

export type McqBankItem = {
  topic: string;
  level: 'A2' | 'B1' | 'B2' | 'C1';
  difficulty: 'easy' | 'hard';
  prompt: string;
  options: [string, string, string, string];
  answerIdx: 0 | 1 | 2 | 3;
  explanation: string;
  tags: string[];
};

export const MCQ_BANK: McqBankItem[] = [
  // ═══════════════════════ GRAMMAR · CONDITIONALS ═══════════════════════
  {
    topic: 'conditionals', level: 'B1', difficulty: 'easy',
    prompt: 'If I ___ more money, I would travel the world.',
    options: ['have', 'had', 'will have', 'would have'],
    answerIdx: 1, explanation: 'Second conditional uses past simple in the if-clause (unreal present).',
    tags: ['grammar', 'conditionals', 'second'],
  },
  {
    topic: 'conditionals', level: 'B2', difficulty: 'easy',
    prompt: 'If she had studied harder, she ___ the exam.',
    options: ['would pass', 'would have passed', 'will pass', 'had passed'],
    answerIdx: 1, explanation: 'Third conditional: past perfect + would have + past participle (imaginary past).',
    tags: ['grammar', 'conditionals', 'third'],
  },
  {
    topic: 'conditionals', level: 'C1', difficulty: 'hard',
    prompt: 'Were I ___ in your position, I would have accepted the offer without further deliberation.',
    options: ['to be', 'be', 'being', 'been'],
    answerIdx: 1, explanation: 'Inverted past subjunctive (formal/literary). "Were I to be" → subjunctive; "be" is the bare subjunctive form.',
    tags: ['grammar', 'conditionals', 'subjunctive', 'formal'],
  },
  {
    topic: 'conditionals', level: 'C1', difficulty: 'hard',
    prompt: 'Had the committee not withdrawn the proposal, the board ___ it by now.',
    options: ['would have approved', 'would approve', 'will have approved', 'had approved'],
    answerIdx: 0, explanation: 'Mixed conditional: past-perfect if-clause + would-have + past participle main clause.',
    tags: ['grammar', 'conditionals', 'mixed', 'c1'],
  },
  {
    topic: 'conditionals', level: 'B1', difficulty: 'easy',
    prompt: 'If it rains tomorrow, we ___ at home.',
    options: ['stay', 'stayed', 'will stay', 'would stay'],
    answerIdx: 2, explanation: 'First conditional: present simple + will + bare infinitive (real future).',
    tags: ['grammar', 'conditionals', 'first'],
  },
  {
    topic: 'conditionals', level: 'B2', difficulty: 'easy',
    prompt: 'If you ___ to the meeting, you would have met the new director.',
    options: ['come', 'came', 'had come', 'would come'],
    answerIdx: 2, explanation: 'Third conditional: past perfect in the if-clause (imaginary past).',
    tags: ['grammar', 'conditionals', 'third'],
  },
  {
    topic: 'conditionals', level: 'C1', difficulty: 'hard',
    prompt: 'But for the timely intervention of the paramedics, the patient ___ ',
    options: ['would have died', 'would die', 'will have died', 'had died'],
    answerIdx: 0, explanation: '"But for" = "If not for" → third conditional (imaginary past).',
    tags: ['grammar', 'conditionals', 'third', 'formal'],
  },

  // ═══════════════════════ GRAMMAR · TENSES ═══════════════════════
  {
    topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'She ___ to the gym every morning.',
    options: ['go', 'goes', 'is going', 'went'], answerIdx: 1,
    explanation: 'Third person singular present simple adds -es: "she goes".',
    tags: ['grammar', 'tenses', 'present-simple'],
  },
  {
    topic: 'tenses', level: 'B1', difficulty: 'easy',
    prompt: 'By the time you arrive, I ___ dinner.',
    options: ['finish', 'will finish', 'will have finished', 'am finishing'], answerIdx: 2,
    explanation: 'Future perfect: action completed before a future point.',
    tags: ['grammar', 'tenses', 'future-perfect'],
  },
  {
    topic: 'tenses', level: 'B2', difficulty: 'easy',
    prompt: 'I ___ for two hours when the phone finally rang.',
    options: ['waited', 'have waited', 'had been waiting', 'was waiting'], answerIdx: 2,
    explanation: 'Past perfect continuous: action ongoing BEFORE another past event.',
    tags: ['grammar', 'tenses', 'past-perfect-continuous'],
  },
  {
    topic: 'tenses', level: 'C1', difficulty: 'hard',
    prompt: 'No sooner ___ down than the doorbell rang.',
    options: ['I had sat', 'had I sat', 'I sat', 'did I sit'], answerIdx: 1,
    explanation: 'Inversion after "no sooner": auxiliary + subject + past participle.',
    tags: ['grammar', 'tenses', 'inversion', 'c1'],
  },
  {
    topic: 'tenses', level: 'C1', difficulty: 'hard',
    prompt: 'The manuscript, ___ by the time the contract was signed, had taken nearly a decade to research.',
    options: ['completing', 'completed', 'having completed', 'to complete'], answerIdx: 1,
    explanation: 'Past participle as a passive reduced relative: "The manuscript (having been) completed".',
    tags: ['grammar', 'tenses', 'participles', 'c1'],
  },
  {
    topic: 'tenses', level: 'B2', difficulty: 'easy',
    prompt: 'By next March, we ___ in this city for ten years.',
    options: ['will live', 'will have been living', 'have lived', 'are living'], answerIdx: 1,
    explanation: 'Future perfect continuous: ongoing action up to a future point.',
    tags: ['grammar', 'tenses', 'future-perfect-continuous'],
  },
  {
    topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'They ___ football when it started to rain.',
    options: ['play', 'played', 'were playing', 'have played'], answerIdx: 2,
    explanation: 'Past continuous: interrupted ongoing action in the past.',
    tags: ['grammar', 'tenses', 'past-continuous', 'a2'],
  },
  {
    topic: 'tenses', level: 'B1', difficulty: 'easy',
    prompt: 'I ___ this novel for three weeks and I still have not finished it.',
    options: ['read', 'have been reading', 'had been reading', 'am reading'], answerIdx: 1,
    explanation: 'Present perfect continuous: action started in the past and still ongoing.',
    tags: ['grammar', 'tenses', 'present-perfect-continuous'],
  },

  // ═══════════════════════ GRAMMAR · ARTICLES ═══════════════════════
  {
    topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: 'I bought ___ umbrella yesterday.',
    options: ['a', 'an', 'the', '—'], answerIdx: 1,
    explanation: '"An" before a vowel SOUND. "Umbrella" starts with /ʌ/.',
    tags: ['grammar', 'articles', 'a2'],
  },
  {
    topic: 'articles', level: 'B2', difficulty: 'hard',
    prompt: '___ United Kingdom comprises ___ England, ___ Scotland, ___ Wales and ___ Northern Ireland.',
    options: ['— / — / — / — / the', 'The / — / — / — / the', 'The / — / — / — / —', '— / the / the / the / the'], answerIdx: 1,
    explanation: 'Country names with "United/Kingdom" take "the". The four constituent countries are used WITHOUT "the" as proper names. Northern Ireland takes "the".',
    tags: ['grammar', 'articles', 'proper-nouns', 'b2'],
  },
  {
    topic: 'articles', level: 'C1', difficulty: 'hard',
    prompt: 'It is ___ most unusual experience; one I shall not soon forget.',
    options: ['a', 'an', 'the', '—'], answerIdx: 3,
    explanation: '"Most" as "very" BEFORE a consonant-sound adjective is used WITHOUT an article.',
    tags: ['grammar', 'articles', 'c1', 'determiners'],
  },
  {
    topic: 'articles', level: 'B2', difficulty: 'easy',
    prompt: 'She is ___ best player on ___ team.',
    options: ['— / a', 'a / the', 'the / the', 'the / a'], answerIdx: 2,
    explanation: '"The best" + superlative; "the team" is a specific team already known.',
    tags: ['grammar', 'articles', 'superlatives'],
  },
  {
    topic: 'articles', level: 'B1', difficulty: 'easy',
    prompt: 'I love ___ music, but I prefer ___ music they played at the wedding.',
    options: ['— / the', 'the / —', '— / —', 'the / the'], answerIdx: 0,
    explanation: 'Zero article for music in general; "the music" for specific music.',
    tags: ['grammar', 'articles', 'b1'],
  },

  // ═══════════════════════ GRAMMAR · PREPOSITIONS ═══════════════════════
  {
    topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'She is good ___ playing the piano.',
    options: ['in', 'at', 'on', 'with'], answerIdx: 1,
    explanation: 'Fixed collocation: "good at" + -ing.',
    tags: ['grammar', 'prepositions', 'a2'],
  },
  {
    topic: 'prepositions', level: 'B1', difficulty: 'easy',
    prompt: 'I am looking forward ___ hearing from you.',
    options: ['to', 'for', 'at', 'in'], answerIdx: 0,
    explanation: '"Look forward to" is followed by a gerund or noun.',
    tags: ['grammar', 'prepositions', 'gerund'],
  },
  {
    topic: 'prepositions', level: 'B2', difficulty: 'easy',
    prompt: 'The decision depends ___ whether the committee approves the budget.',
    options: ['of', 'on', 'from', 'to'], answerIdx: 1,
    explanation: '"Depend on" is the verb + preposition collocation.',
    tags: ['grammar', 'prepositions', 'b2'],
  },
  {
    topic: 'prepositions', level: 'C1', difficulty: 'hard',
    prompt: 'His remarks, far ___ being off the cuff, were carefully prepared and rehearsed.',
    options: ['from', 'off', 'of', 'to'], answerIdx: 0,
    explanation: 'Idiomatic "far from + -ing" = "not at all + -ing" (emphatic negation).',
    tags: ['grammar', 'prepositions', 'idioms', 'c1'],
  },
  {
    topic: 'prepositions', level: 'B2', difficulty: 'easy',
    prompt: 'We should arrive ___ time for the meeting.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 2,
    explanation: 'No idiom. "In time" = not late; "on time" = punctual to schedule.',
    tags: ['grammar', 'prepositions', 'time'],
  },
  {
    topic: 'prepositions', level: 'C1', difficulty: 'hard',
    prompt: 'Her performance was characterized ___ a remarkable restraint.',
    options: ['of', 'by', 'with', 'for'], answerIdx: 1,
    explanation: '"Characterized by" = marked by / typified by. "With" collocates with "character" but not the verb "characterize".',
    tags: ['grammar', 'prepositions', 'c1'],
  },

  // ═══════════════════════ GRAMMAR · MODALS ═══════════════════════
  {
    topic: 'modals', level: 'B1', difficulty: 'easy',
    prompt: 'You ___ finish your homework before watching TV.',
    options: ['must', 'should', 'have to', 'can'], answerIdx: 0,
    explanation: '"Must" expresses strong personal obligation (speaker insists).',
    tags: ['grammar', 'modals', 'obligation'],
  },
  {
    topic: 'modals', level: 'B2', difficulty: 'easy',
    prompt: 'You ___ have left your bag at the cafe — it is not in your locker.',
    options: ['must', 'should', 'might', 'can'], answerIdx: 2,
    explanation: '"Might" = possibility (50/50). "Must" is too strong here.',
    tags: ['grammar', 'modals', 'deduction'],
  },
  {
    topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'Under no circumstances ___ the safety mechanism be disengaged while the device is operational.',
    options: ['must', 'should', 'shall', 'may'], answerIdx: 2,
    explanation: 'Inverted subjunctive after "under no circumstances" → bare infinitive.',
    tags: ['grammar', 'modals', 'formal', 'inversion'],
  },
  {
    topic: 'modals', level: 'B2', difficulty: 'easy',
    prompt: 'He ___ have taken the train; the station was closed by the time he arrived.',
    options: ['couldn\'t', 'mustn\'t', 'shouldn\'t', 'won\'t'], answerIdx: 0,
    explanation: '"Couldn\'t have + pp" = past logical impossibility.',
    tags: ['grammar', 'modals', 'past-deduction'],
  },
  {
    topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'You ___ have warned me about the meeting; I would have come prepared.',
    options: ['should', 'might', 'could', 'would'], answerIdx: 2,
    explanation: '"Could have + pp" = past ability / opportunity missed. Soft regret, weaker than "should have".',
    tags: ['grammar', 'modals', 'c1'],
  },

  // ═══════════════════════ GRAMMAR · PASSIVES ═══════════════════════
  {
    topic: 'passives', level: 'B1', difficulty: 'easy',
    prompt: 'The cake ___ by Maria yesterday.',
    options: ['is baked', 'was baked', 'has baked', 'bakes'], answerIdx: 1,
    explanation: 'Past simple passive: was/were + past participle.',
    tags: ['grammar', 'passives', 'past'],
  },
  {
    topic: 'passives', level: 'B2', difficulty: 'easy',
    prompt: 'The new bridge ___ at the moment, so traffic is being rerouted.',
    options: ['is repaired', 'is being repaired', 'has been repaired', 'repairs'], answerIdx: 1,
    explanation: 'Present continuous passive: is/are + being + past participle.',
    tags: ['grammar', 'passives', 'present-continuous'],
  },
  {
    topic: 'passives', level: 'C1', difficulty: 'hard',
    prompt: 'The witness is believed ___ the country shortly after the incident.',
    options: ['to leave', 'to have left', 'leaving', 'having leave'], answerIdx: 1,
    explanation: 'Reporting verbs + passive "to have + pp" for past events.',
    tags: ['grammar', 'passives', 'reporting', 'c1'],
  },
  {
    topic: 'passives', level: 'B2', difficulty: 'easy',
    prompt: 'This film ___ by Steven Spielberg.',
    options: ['directed', 'was directed', 'has directed', 'directs'], answerIdx: 1,
    explanation: 'Past simple passive for a finished action by a known agent.',
    tags: ['grammar', 'passives', 'b2'],
  },

  // ═══════════════════════ GRAMMAR · RELATIVE CLAUSES ═══════════════════════
  {
    topic: 'relative-clauses', level: 'B1', difficulty: 'easy',
    prompt: 'The man ___ car was stolen called the police.',
    options: ['which', 'who', 'whose', 'whom'], answerIdx: 2,
    explanation: '"Whose" expresses possession (= "of whom").',
    tags: ['grammar', 'relative-clauses', 'b1'],
  },
  {
    topic: 'relative-clauses', level: 'B2', difficulty: 'easy',
    prompt: 'The book ___ I bought yesterday is on the table.',
    options: ['who', 'which', 'whom', 'whose'], answerIdx: 1,
    explanation: '"Which" for things; "who/whom" for people.',
    tags: ['grammar', 'relative-clauses', 'b2'],
  },
  {
    topic: 'relative-clauses', level: 'C1', difficulty: 'hard',
    prompt: 'He cited several concerns, not the least of ___ being the long-term environmental impact.',
    options: ['them', 'which', 'those', 'whom'], answerIdx: 1,
    explanation: '"Not the least of which" = "and importantly among them".',
    tags: ['grammar', 'relative-clauses', 'formal', 'c1'],
  },
  {
    topic: 'relative-clauses', level: 'B2', difficulty: 'easy',
    prompt: 'The hotel ___ we stayed was very expensive.',
    options: ['that', 'which', 'where', 'who'], answerIdx: 2,
    explanation: '"Where" for places (= "in which" / "at which").',
    tags: ['grammar', 'relative-clauses', 'b2'],
  },

  // ═══════════════════════ GRAMMAR · REPORTING ═══════════════════════
  {
    topic: 'reporting', level: 'B2', difficulty: 'easy',
    prompt: 'She told me that she ___ tired.',
    options: ['is', 'was', 'has been', 'were'], answerIdx: 1,
    explanation: 'Reported speech shifts tense back: "I am tired" → "she was tired".',
    tags: ['grammar', 'reporting', 'tense-shift'],
  },
  {
    topic: 'reporting', level: 'C1', difficulty: 'hard',
    prompt: 'The minister denied that the funds ___ misappropriated or that any impropriety ___ place.',
    options: ['had been / had taken', 'were / took', 'have been / has taken', 'had been / has taken'], answerIdx: 0,
    explanation: 'Past perfect passive + past perfect "taken place".',
    tags: ['grammar', 'reporting', 'c1'],
  },
  {
    topic: 'reporting', level: 'B2', difficulty: 'easy',
    prompt: 'He asked me where I ___ the previous summer.',
    options: ['have been', 'had been', 'was being', 'would be'], answerIdx: 1,
    explanation: 'Past perfect for an event further back in time than the reporting verb.',
    tags: ['grammar', 'reporting', 'b2'],
  },

  // ═══════════════════════ VOCAB · PHRASAL VERBS ═══════════════════════
  {
    topic: 'phrasal-verbs', level: 'B1', difficulty: 'easy',
    prompt: 'I need to ___ this report before the deadline.',
    options: ['look up', 'put off', 'finish up', 'take off'], answerIdx: 2,
    explanation: '"Finish up" = complete the remainder of something.',
    tags: ['vocab', 'phrasal-verbs', 'b1'],
  },
  {
    topic: 'phrasal-verbs', level: 'B2', difficulty: 'easy',
    prompt: 'Could you ___ the volume? I can not hear the speaker.',
    options: ['turn up', 'turn down', 'turn off', 'turn over'], answerIdx: 0,
    explanation: '"Turn up" = increase. "Turn down" = decrease or reject (an offer).',
    tags: ['vocab', 'phrasal-verbs', 'b2'],
  },
  {
    topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'The new policy appears to ___ short of addressing the root causes of the problem.',
    options: ['come up', 'come down', 'come by', 'come off'], answerIdx: 0,
    explanation: '"Come up short" = fall short of expectations.',
    tags: ['vocab', 'phrasal-verbs', 'idioms', 'c1'],
  },
  {
    topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'After months of negotiations, the parties finally ___ a compromise that satisfied no one entirely.',
    options: ['came up with', 'came down to', 'came about', 'came into'], answerIdx: 0,
    explanation: '"Come up with" = produce / devise.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  {
    topic: 'phrasal-verbs', level: 'B2', difficulty: 'easy',
    prompt: 'The committee ___ the proposal after a long debate.',
    options: ['brought up', 'brought about', 'brought down', 'brought forward'], answerIdx: 0,
    explanation: '"Bring up" = introduce for discussion.',
    tags: ['vocab', 'phrasal-verbs', 'b2'],
  },
  {
    topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'The witness was reluctant to ___ the names of his accomplices.',
    options: ['give away', 'give in', 'give up', 'give off'], answerIdx: 0,
    explanation: '"Give away" = reveal (a secret). "Give in" = surrender.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  {
    topic: 'phrasal-verbs', level: 'B1', difficulty: 'easy',
    prompt: 'Could you ___ the lights when you leave?',
    options: ['put out', 'put off', 'put down', 'put up'], answerIdx: 0,
    explanation: '"Put out" (fire, lights, cigarette) = extinguish.',
    tags: ['vocab', 'phrasal-verbs', 'b1'],
  },

  // ═══════════════════════ VOCAB · IELTS / ACADEMIC ═══════════════════════
  {
    topic: 'vocab-ielts', level: 'B2', difficulty: 'easy',
    prompt: 'Choose the word closest in meaning to ABUNDANT:',
    options: ['scarce', 'plentiful', 'minimal', 'moderate'], answerIdx: 1,
    explanation: '"Abundant" = plentiful, more than enough. Antonym: scarce.',
    tags: ['vocab', 'ielts', 'synonyms'],
  },
  {
    topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The new evidence appears to UNDERMINE, rather than support, the prosecution\'s case.',
    options: ['weaken', 'strengthen', 'clarify', 'discredit'], answerIdx: 1,
    explanation: '"Undermine" = weaken; the sentence says the evidence SUPPORTS it (the inversion flips meaning).',
    tags: ['vocab', 'ielts', 'c1', 'negation'],
  },
  {
    topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The scientist\'s conclusion, while not strictly INCONSISTENT with the data, is hardly COMPELLING either.',
    options: ['incompatible / persuasive', 'conflicting / convincing', 'compatible / persuasive', 'similar / uninteresting'], answerIdx: 0,
    explanation: '"Inconsistent" = not compatible; "compelling" = persuasive.',
    tags: ['vocab', 'ielts', 'c1', 'synonyms'],
  },
  {
    topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The findings of the meta-analysis were largely CORROBORATED by independent researchers.',
    options: ['contradicted', 'confirmed', 'overlooked', 'refuted'], answerIdx: 1,
    explanation: '"Corroborated" = confirmed / supported by evidence.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  {
    topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The minister\'s response was deliberately EQUIVOCAL, neither confirming nor denying the allegations.',
    options: ['clear', 'ambiguous', 'emphatic', 'lengthy'], answerIdx: 1,
    explanation: '"Equivocal" = ambiguous, intentionally unclear.',
    tags: ['vocab', 'ielts', 'c1'],
  },

  // ═══════════════════════ VOCAB · FALSE COGNATES ═══════════════════════
  {
    topic: 'false-cognates', level: 'B2', difficulty: 'easy',
    prompt: 'He made a SENSIBLE suggestion that everyone agreed with.',
    options: ['sensitive', 'reasonable', 'sensory', 'sensational'], answerIdx: 1,
    explanation: '"Sensible" = practical / reasonable.',
    tags: ['vocab', 'false-cognates'],
  },
  {
    topic: 'false-cognates', level: 'C1', difficulty: 'hard',
    prompt: 'The politician\'s SYMPATHETIC response to the crisis was widely praised.',
    options: ['showing pity', 'in agreement', 'showing enthusiasm', 'expressing doubt'], answerIdx: 1,
    explanation: '"Sympathetic" = supportive / showing agreement.',
    tags: ['vocab', 'false-cognates', 'c1'],
  },

  // ═══════════════════════ VOCAB · COLLOCATIONS ═══════════════════════
  {
    topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'The doctor ___ a thorough examination before making a diagnosis.',
    options: ['did', 'made', 'took', 'had'], answerIdx: 0,
    explanation: '"Do / perform / carry out" an examination.',
    tags: ['vocab', 'collocations'],
  },
  {
    topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'She ___ a strong decision to leave her job.',
    options: ['did', 'made', 'took', 'got'], answerIdx: 1,
    explanation: '"Make a decision" is the only natural collocation.',
    tags: ['vocab', 'collocations'],
  },
  {
    topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'We need to ___ an effort to reduce waste.',
    options: ['make', 'do', 'take', 'have'], answerIdx: 0,
    explanation: '"Make an effort" — fixed.',
    tags: ['vocab', 'collocations'],
  },
  {
    topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'The two companies reached a ___ after weeks of negotiation.',
    options: ['deal', 'do', 'make', 'have'], answerIdx: 0,
    explanation: '"Reach / strike a deal" — fixed.',
    tags: ['vocab', 'collocations'],
  },

  // ═══════════════════════ GRAMMAR · SUBJUNCTIVE ═══════════════════════
  {
    topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'The board insisted that the report ___ by Friday without exception.',
    options: ['be submitted', 'is submitted', 'was submitted', 'will be submitted'], answerIdx: 0,
    explanation: 'Subjunctive after "insist / demand / suggest" → base form.',
    tags: ['grammar', 'subjunctive', 'c1'],
  },
  {
    topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'It is essential that every member ___ present at the roll call.',
    options: ['is', 'be', 'was', 'will be'], answerIdx: 1,
    explanation: 'Subjunctive after "essential / vital / crucial" → base form.',
    tags: ['grammar', 'subjunctive', 'c1'],
  },

  // ═══════════════════════ GRAMMAR · INVERSION ═══════════════════════
  {
    topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Rarely ___ such an impressive performance from a debut author.',
    options: ['I have seen', 'have I seen', 'I had seen', 'did I see'], answerIdx: 1,
    explanation: 'Negative adverbial "Rarely" + inversion.',
    tags: ['grammar', 'inversion', 'c1'],
  },
  {
    topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Not until the data were independently verified ___ the paper for publication.',
    options: ['the editor accepted', 'did the editor accept', 'the editor had accepted', 'accepted the editor'], answerIdx: 1,
    explanation: '"Not until" + inversion.',
    tags: ['grammar', 'inversion', 'c1'],
  },

  // ═══════════════════════ GRAMMAR · LINKERS ═══════════════════════
  {
    topic: 'linkers', level: 'B2', difficulty: 'easy',
    prompt: '___ being late, he had forgotten his keys.',
    options: ['Despite', 'Although', 'In spite', 'Whereas'], answerIdx: 0,
    explanation: '"Despite" + -ing or noun.',
    tags: ['grammar', 'linkers'],
  },
  {
    topic: 'linkers', level: 'C1', difficulty: 'hard',
    prompt: 'The project was abandoned, _______ the considerable time and money already invested.',
    options: ['despite', 'although', 'in spite of', 'notwithstanding'], answerIdx: 3,
    explanation: '"Notwithstanding" is the formal option that fits without rewording.',
    tags: ['grammar', 'linkers', 'c1'],
  },

  // ═══════════════════════ VOCAB · IDIOMS ═══════════════════════
  {
    topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'To ___ the bucket means to die (informal).',
    options: ['kick', 'spill', 'throw', 'drop'], answerIdx: 0,
    explanation: '"Kick the bucket" = die.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  {
    topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'The new manager is ___ in the same boat as the rest of the team when it comes to budget cuts.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 0,
    explanation: '"In the same boat" = in the same difficult situation.',
    tags: ['vocab', 'idioms', 'c1'],
  },

  // ═══════════════════════ GRAMMAR · GERUND / INFINITIVE ═══════════════════════
  {
    topic: 'gerund-infinitive', level: 'B2', difficulty: 'easy',
    prompt: 'I enjoy ___ to classical music in the evening.',
    options: ['to listen', 'listening', 'listen', 'listened'], answerIdx: 1,
    explanation: 'After "enjoy / avoid / mind / suggest" use the gerund.',
    tags: ['grammar', 'gerund-infinitive'],
  },
  {
    topic: 'gerund-infinitive', level: 'B2', difficulty: 'hard',
    prompt: 'I ___ rather you ___ that to anyone.',
    options: ['would / didn\'t say', 'would / don\'t say', 'will / not say', 'should / won\'t say'], answerIdx: 0,
    explanation: '"Would rather" + past tense refers to the present action of someone else.',
    tags: ['grammar', 'gerund-infinitive', 'b2'],
  },

  // ═══════════════════════ VOCAB · WORDS EASILY CONFUSED ═══════════════════════
  {
    topic: 'confused-words', level: 'B2', difficulty: 'easy',
    prompt: 'I would ___ to say that the situation is improving.',
    options: ['tend', 'intend', 'attend', 'pretend'], answerIdx: 0,
    explanation: '"Tend to" = be inclined to.',
    tags: ['vocab', 'confused-words'],
  },
  {
    topic: 'confused-words', level: 'B2', difficulty: 'hard',
    prompt: 'The new manager is ___ to make sweeping changes without consulting the team.',
    options: ['want to', 'wanting', 'wants', 'wanted'], answerIdx: 2,
    explanation: 'Third person singular present simple: "the manager wants".',
    tags: ['vocab', 'confused-words'],
  },

  // ═══════════════════════ GRAMMAR · QUESTIONS ═══════════════════════
  {
    topic: 'questions', level: 'B1', difficulty: 'easy',
    prompt: '___ you ever been to Japan?',
    options: ['Do', 'Have', 'Did', 'Are'], answerIdx: 1,
    explanation: 'Present perfect asks about life experience.',
    tags: ['grammar', 'questions'],
  },
  {
    topic: 'questions', level: 'C1', difficulty: 'hard',
    prompt: '___ that the committee would approve the proposal, we proceeded with the implementation.',
    options: ['Telling', 'Having told', 'Being told', 'Having been told'], answerIdx: 3,
    explanation: '"Having been told" = passive prior action before "we proceeded".',
    tags: ['grammar', 'questions', 'c1', 'participles'],
  },

  // ═══════════════════════ GRAMMAR · COMPARISON ═══════════════════════
  {
    topic: 'comparison', level: 'B1', difficulty: 'easy',
    prompt: 'This book is ___ interesting than the previous one.',
    options: ['more', 'most', 'much', 'very'], answerIdx: 0,
    explanation: 'Comparative of "interesting" (long adj) uses "more".',
    tags: ['grammar', 'comparison'],
  },
  {
    topic: 'comparison', level: 'C1', difficulty: 'hard',
    prompt: 'The new proposal is ___ the more thoughtful of the two.',
    options: ['by far', 'by much', 'by far', 'by big'], answerIdx: 0,
    explanation: '"By far the more X" intensifies a comparative.',
    tags: ['grammar', 'comparison', 'c1'],
  },

  // ═══════════════════════ VOCAB · WORD FORMATION ═══════════════════════
  {
    topic: 'word-formation', level: 'B2', difficulty: 'easy',
    prompt: 'The scientist made a remarkable ___ at the conference.',
    options: ['discover', 'discovery', 'discovered', 'discovering'], answerIdx: 1,
    explanation: 'After "a" we need a noun; "-y" forms "discovery".',
    tags: ['vocab', 'word-formation'],
  },
  {
    topic: 'word-formation', level: 'C1', difficulty: 'hard',
    prompt: 'His arguments were so ___ that nobody could dispute them.',
    options: ['compelling', 'compellingly', 'compel', 'compelled'], answerIdx: 0,
    explanation: 'After "were" we need an adjective.',
    tags: ['vocab', 'word-formation', 'c1'],
  },

  // ═══════════════════════ VOCAB · SPELLING ═══════════════════════
  {
    topic: 'spelling', level: 'B1', difficulty: 'easy',
    prompt: 'Choose the correctly spelled word:',
    options: ['recieve', 'receive', 'receeve', 'receeve'], answerIdx: 1,
    explanation: '"I before E except after C": receive.',
    tags: ['vocab', 'spelling'],
  },
  {
    topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Choose the word that fits: "The data were ___ according to the latest protocol."',
    options: ['omitted', 'emitted', 'admitted', 'remitted'], answerIdx: 0,
    explanation: '"Omitted" = left out. "Emitted" = sent out (radiation/gas); "admitted" = confessed; "remitted" = sent (payment).',
    tags: ['vocab', 'spelling', 'c1'],
  },

  // ═══════════════════════ MORE — to clear 150+ ═══════════════════════

  // GRAMMAR — extra
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'Yesterday, I ___ a new book at the store.',
    options: ['buy', 'bought', 'have bought', 'am buying'], answerIdx: 1,
    explanation: 'Past simple for a finished action at a specific past time.',
    tags: ['grammar', 'tenses', 'past-simple'],
  },
  { topic: 'tenses', level: 'B1', difficulty: 'easy',
    prompt: 'I ___ never ___ sushi before I visited Japan last year.',
    options: ['have / tried', 'had / tried', 'did / try', 'was / trying'], answerIdx: 1,
    explanation: 'Past perfect for an event before another past event.',
    tags: ['grammar', 'tenses', 'past-perfect'],
  },
  { topic: 'tenses', level: 'B2', difficulty: 'easy',
    prompt: 'By the time we get there, the film ___ ',
    options: ['will start', 'will have started', 'starts', 'is starting'], answerIdx: 1,
    explanation: 'Future perfect: action completed before a future point.',
    tags: ['grammar', 'tenses', 'future-perfect'],
  },
  { topic: 'modals', level: 'B1', difficulty: 'easy',
    prompt: '___ I borrow your pen, please?',
    options: ['Must', 'Should', 'May', 'Would'], answerIdx: 2,
    explanation: '"May" is the formal polite request for permission.',
    tags: ['grammar', 'modals', 'permission'],
  },
  { topic: 'modals', level: 'B1', difficulty: 'easy',
    prompt: 'You ___ not smoke in here. It is against the rules.',
    options: ['must', 'should', 'ought', 'may'], answerIdx: 0,
    explanation: '"Must not" = prohibition.',
    tags: ['grammar', 'modals', 'prohibition'],
  },
  { topic: 'modals', level: 'B2', difficulty: 'hard',
    prompt: 'She ___ have passed the exam, but she missed the deadline.',
    options: ['might', 'should', 'could', 'would'], answerIdx: 2,
    explanation: '"Could have + pp" = past ability missed (regret).',
    tags: ['grammar', 'modals', 'past-ability'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'I will see you ___ Monday morning.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 1,
    explanation: '"On" for days and dates; "in" for months/years; "at" for times.',
    tags: ['grammar', 'prepositions', 'time'],
  },
  { topic: 'prepositions', level: 'B1', difficulty: 'easy',
    prompt: 'He is afraid ___ spiders.',
    options: ['of', 'from', 'with', 'by'], answerIdx: 0,
    explanation: '"Afraid of" — fixed.',
    tags: ['grammar', 'prepositions', 'emotion'],
  },
  { topic: 'prepositions', level: 'B2', difficulty: 'hard',
    prompt: 'Her argument is not entirely ___ to the question at hand.',
    options: ['relevant', 'relative', 'related', 'reliable'], answerIdx: 0,
    explanation: '"Relevant to" = pertinent. "Related to" = connected; "relative to" = comparative; "reliable" = trustworthy.',
    tags: ['grammar', 'prepositions', 'vocab'],
  },
  { topic: 'articles', level: 'B1', difficulty: 'easy',
    prompt: '___ Eiffel Tower is in Paris.',
    options: ['A', 'An', 'The', '—'], answerIdx: 2,
    explanation: 'Famous landmarks take "the".',
    tags: ['grammar', 'articles'],
  },
  { topic: 'articles', level: 'B2', difficulty: 'easy',
    prompt: 'She plays ___ piano and ___ guitar.',
    options: ['— / —', 'the / the', 'the / —', '— / the'], answerIdx: 1,
    explanation: 'Musical instruments take "the" (the definite article).',
    tags: ['grammar', 'articles'],
  },
  { topic: 'articles', level: 'C1', difficulty: 'hard',
    prompt: '___ Himalayas are the highest mountain range in ___ world.',
    options: ['— / the', 'The / the', 'The / a', '— / —'], answerIdx: 1,
    explanation: 'Mountain ranges in plural + "the"; "the world" is unique.',
    tags: ['grammar', 'articles', 'c1'],
  },

  // VOCAB — extra
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The minister was UNREMITTING in his pursuit of reform.',
    options: ['lazy', 'persistent', 'brief', 'hesitant'], answerIdx: 1,
    explanation: '"Unremitting" = never stopping / persistent.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The findings were CONGRUENT with previous studies.',
    options: ['inconsistent', 'similar', 'opposed', 'irrelevant'], answerIdx: 1,
    explanation: '"Congruent" = in agreement / matching.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'B2', difficulty: 'easy',
    prompt: 'Choose the closest synonym for MITIGATE:',
    options: ['worsen', 'lessen', 'ignore', 'explain'], answerIdx: 1,
    explanation: '"Mitigate" = make less severe / reduce.',
    tags: ['vocab', 'ielts'],
  },
  { topic: 'vocab-ielts', level: 'B2', difficulty: 'easy',
    prompt: 'Choose the closest synonym for PROFOUND:',
    options: ['shallow', 'deep', 'wide', 'cheap'], answerIdx: 1,
    explanation: '"Profound" = very deep / intense.',
    tags: ['vocab', 'ielts'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The proposal was met with STIFF resistance from the committee.',
    options: ['weak', 'strong', 'flexible', 'half-hearted'], answerIdx: 1,
    explanation: '"Stiff" (metaphorical) = strong / unyielding.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'phrasal-verbs', level: 'B1', difficulty: 'easy',
    prompt: 'Please ___ the form and submit it at the desk.',
    options: ['fill in', 'fill up', 'fill out', 'fill for'], answerIdx: 0,
    explanation: '"Fill in" = complete (a form). "Fill up" = make full.',
    tags: ['vocab', 'phrasal-verbs'],
  },
  { topic: 'phrasal-verbs', level: 'B2', difficulty: 'easy',
    prompt: 'Could you ___ the bill, please?',
    options: ['pick up', 'pick out', 'pick at', 'pick on'], answerIdx: 0,
    explanation: '"Pick up the bill" = pay (US informal). "Pick on" = bully.',
    tags: ['vocab', 'phrasal-verbs'],
  },
  { topic: 'phrasal-verbs', level: 'B2', difficulty: 'hard',
    prompt: 'I will ___ for the meeting at 9 AM.',
    options: ['set off', 'set up', 'set out', 'set down'], answerIdx: 0,
    explanation: '"Set off" = begin a journey. "Set up" = arrange / establish.',
    tags: ['vocab', 'phrasal-verbs', 'b2'],
  },
  { topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'The lawyer managed to ___ a plea bargain for his client.',
    options: ['work out', 'work on', 'work off', 'work up'], answerIdx: 0,
    explanation: '"Work out" = arrange / resolve. "Work off" = reduce (a debt) by effort.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  { topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'I cannot ___ with his constant complaining any longer.',
    options: ['put up', 'put off', 'put away', 'put aside'], answerIdx: 0,
    explanation: '"Put up with" = tolerate.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },

  // MORE VOCAB: false cognates, word formation, confused words
  { topic: 'false-cognates', level: 'B2', difficulty: 'easy',
    prompt: 'The novel had a very SENSIBLE plot twist.',
    options: ['sensitive', 'reasonable', 'sensory', 'sensational'], answerIdx: 3,
    explanation: '"Sensational" = causing great public excitement. "Sensible" = reasonable.',
    tags: ['vocab', 'false-cognates'],
  },
  { topic: 'false-cognates', level: 'C1', difficulty: 'hard',
    prompt: 'Her REMARK was widely quoted.',
    options: ['remark', 'remarking', 'remarkable', 'remarkably'], answerIdx: 0,
    explanation: 'After "a" we need a noun: "remark". "Remarkable" is an adjective.',
    tags: ['vocab', 'false-cognates', 'c1'],
  },
  { topic: 'word-formation', level: 'B2', difficulty: 'easy',
    prompt: 'The ___ of the new product was widely covered in the media.',
    options: ['launch', 'launching', 'launched', 'launches'], answerIdx: 0,
    explanation: 'After "the" we need a noun: "launch".',
    tags: ['vocab', 'word-formation'],
  },
  { topic: 'word-formation', level: 'C1', difficulty: 'hard',
    prompt: 'Her explanation was so ___ that the entire room fell silent.',
    options: ['compelling', 'compellingly', 'compel', 'compelled'], answerIdx: 0,
    explanation: 'After "was" we need an adjective.',
    tags: ['vocab', 'word-formation', 'c1'],
  },
  { topic: 'confused-words', level: 'B2', difficulty: 'easy',
    prompt: 'The doctor advised him to ___ more exercise.',
    options: ['take', 'make', 'do', 'have'], answerIdx: 0,
    explanation: '"Take exercise" = exercise. "Do exercise" = perform exercises.',
    tags: ['vocab', 'confused-words', 'collocations'],
  },
  { topic: 'confused-words', level: 'C1', difficulty: 'hard',
    prompt: 'Her argument is based on the ASSUMPTION that the data are reliable.',
    options: ['consumption', 'assumption', 'presumption', 'resumption'], answerIdx: 1,
    explanation: '"Assumption" = belief without proof. "Presumption" = bolder, more pejorative.',
    tags: ['vocab', 'confused-words', 'c1'],
  },
  { topic: 'confused-words', level: 'C1', difficulty: 'hard',
    prompt: 'The report was published ___ the supervision of Dr. Lin.',
    options: ['under', 'below', 'beneath', 'lower'], answerIdx: 0,
    explanation: '"Under the supervision of" — fixed collocation.',
    tags: ['vocab', 'confused-words', 'collocations'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'Let us ___ the elephant in the room: we are running out of time.',
    options: ['address', 'avoid', 'ignore', 'forget'], answerIdx: 0,
    explanation: '"Address the elephant in the room" = confront the obvious problem everyone is avoiding.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'His proposal is a win-___ situation: both sides benefit.',
    options: ['win', 'lose', 'all', 'over'], answerIdx: 0,
    explanation: '"Win-win" — both sides gain.',
    tags: ['vocab', 'idioms'],
  },

  // GRAMMAR — extra hard
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Hardly ___ the meeting when the fire alarm went off.',
    options: ['we had begun', 'had we begun', 'we began', 'did we begin'], answerIdx: 1,
    explanation: '"Hardly" + inversion + past perfect (the meeting had only just begun).',
    tags: ['grammar', 'inversion', 'c1'],
  },
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Only after the audit ___ that several invoices were missing.',
    options: ['we discovered', 'did we discover', 'we had discovered', 'had we discover'], answerIdx: 1,
    explanation: '"Only after" + inversion + simple past.',
    tags: ['grammar', 'inversion', 'c1'],
  },
  { topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'The chair recommended that the motion ___ before lunch.',
    options: ['be voted on', 'is voted on', 'was voted on', 'will be voted on'], answerIdx: 0,
    explanation: 'Subjunctive after "recommend" → base form of passive.',
    tags: ['grammar', 'subjunctive', 'c1'],
  },
  { topic: 'reporting', level: 'C1', difficulty: 'hard',
    prompt: 'He reminded me that the deadline ___ at midnight.',
    options: ['is', 'was', 'had been', 'has been'], answerIdx: 0,
    explanation: 'Reporting verb in the present (reminded) keeps the original tense; the deadline IS at midnight (still true).',
    tags: ['grammar', 'reporting', 'c1'],
  },
  { topic: 'relative-clauses', level: 'C1', difficulty: 'hard',
    prompt: 'The committee reached a decision, ___ effect will be felt across the organization.',
    options: ['that', 'whose', 'which', 'whom'], answerIdx: 1,
    explanation: '"Whose" for possession (= "of which"). "Which" without "also" doesn\'t show possession here.',
    tags: ['grammar', 'relative-clauses', 'c1'],
  },
  { topic: 'passives', level: 'C1', difficulty: 'hard',
    prompt: 'The suspect is reported ___ shortly after the robbery.',
    options: ['to flee', 'to have fled', 'fleeing', 'having flee'], answerIdx: 1,
    explanation: '"Is reported to have + pp" for reported past action.',
    tags: ['grammar', 'passives', 'reporting', 'c1'],
  },
  { topic: 'passives', level: 'C1', difficulty: 'hard',
    prompt: 'The proposal ought to ___ before the end of the week.',
    options: ['complete', 'be completed', 'have completed', 'completing'], answerIdx: 1,
    explanation: '"Ought to" + passive "be completed" (modal passive).',
    tags: ['grammar', 'passives', 'modals', 'c1'],
  },
  { topic: 'gerund-infinitive', level: 'C1', difficulty: 'hard',
    prompt: 'I appreciate ___ the opportunity to address the committee today.',
    options: ['to have', 'having', 'to be had', 'have'], answerIdx: 1,
    explanation: '"Appreciate" + gerund. "I appreciate having been given the opportunity" = "I am grateful that I was given".',
    tags: ['grammar', 'gerund-infinitive', 'c1'],
  },
  { topic: 'comparison', level: 'B2', difficulty: 'easy',
    prompt: 'This is the ___ book I have ever read on the subject.',
    options: ['most interesting', 'more interesting', 'interesting', 'interestinger'], answerIdx: 0,
    explanation: 'Superlative of "interesting" (long adj) uses "the most".',
    tags: ['grammar', 'comparison'],
  },
  { topic: 'comparison', level: 'C1', difficulty: 'hard',
    prompt: 'The more you practise, ___ you will become.',
    options: ['the more fluent', 'more fluent', 'fluenter', 'fluent'], answerIdx: 0,
    explanation: '"The more ... the more" comparative correlative construction.',
    tags: ['grammar', 'comparison', 'c1'],
  },
  { topic: 'questions', level: 'B2', difficulty: 'easy',
    prompt: 'How long ___ English?',
    options: ['do you learn', 'are you learning', 'have you been learning', 'you are learning'], answerIdx: 2,
    explanation: 'Present perfect continuous: action started in the past and still continuing.',
    tags: ['grammar', 'questions'],
  },
  { topic: 'questions', level: 'C1', difficulty: 'hard',
    prompt: 'Rarely ___ such an impressive debut from a first-time author.',
    options: ['I have read', 'have I read', 'I had read', 'did I read'], answerIdx: 1,
    explanation: 'Negative adverbial "Rarely" + inversion; present perfect for life experience.',
    tags: ['grammar', 'questions', 'inversion', 'c1'],
  },
  { topic: 'linkers', level: 'B2', difficulty: 'easy',
    prompt: 'We stayed inside ___ it was raining heavily.',
    options: ['despite', 'although', 'because', 'however'], answerIdx: 2,
    explanation: '"Because" introduces a cause; "although" introduces a concession.',
    tags: ['grammar', 'linkers'],
  },
  { topic: 'linkers', level: 'C1', difficulty: 'hard',
    prompt: '___ the heavy rain, the event went ahead as planned.',
    options: ['Despite', 'Although', 'In spite', 'Whereas'], answerIdx: 0,
    explanation: '"Despite" + noun phrase; "Although" would need a clause.',
    tags: ['grammar', 'linkers'],
  },

  // MORE VOCAB / IDIOMS
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'The new evidence threw a ___ into the investigation.',
    options: ['spanner', 'monkey wrench', 'wrench', 'screwdriver'], answerIdx: 0,
    explanation: '"Throw a spanner into the works" = disrupt a plan.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'Her remarks were taken out of ___.',
    options: ['context', 'order', 'the blue', 'the question'], answerIdx: 0,
    explanation: '"Out of context" = removed from the surrounding situation.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'Let us get straight to the ___: are you free on Friday?',
    options: ['point', 'place', 'matter', 'subject'], answerIdx: 0,
    explanation: '"Straight to the point" = without preamble.',
    tags: ['vocab', 'idioms'],
  },

  // SPELLING
  { topic: 'spelling', level: 'B2', difficulty: 'easy',
    prompt: 'Choose the correctly spelled word:',
    options: ['definately', 'definitely', 'definitly', 'definately'], answerIdx: 1,
    explanation: '"Definitely" — i before te.',
    tags: ['vocab', 'spelling'],
  },
  { topic: 'spelling', level: 'B2', difficulty: 'easy',
    prompt: 'Choose the correctly spelled word:',
    options: ['occured', 'occurred', 'occurrred', 'ocurred'], answerIdx: 1,
    explanation: '"Occurred" — double c, double r.',
    tags: ['vocab', 'spelling'],
  },
  { topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Choose the word that fits: "The scientist ___ the data over several weeks."',
    options: ['analyzed', 'analysed', 'analyzed / analysed', 'analized'], answerIdx: 2,
    explanation: 'Both spellings are correct (US / UK). The other two are misspellings.',
    tags: ['vocab', 'spelling', 'c1'],
  },

  // VOCAB — IELTS more
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The two approaches are largely EQUIVALENT in their outcomes.',
    options: ['different', 'similar', 'opposite', 'contradictory'], answerIdx: 1,
    explanation: '"Equivalent" = equal in value / similar in effect.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'She gave a LUCID explanation that everyone could follow.',
    options: ['confusing', 'brief', 'clear', 'lengthy'], answerIdx: 2,
    explanation: '"Lucid" = easy to understand / transparent.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'His speech was MARRED by a series of unfortunate slips.',
    options: ['enhanced', 'improved', 'spoiled', 'uninterrupted'], answerIdx: 2,
    explanation: '"Marred" = spoiled / impaired.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The new policy has come under FIRE from opposition leaders.',
    options: ['praise', 'attack', 'support', 'neglect'], answerIdx: 1,
    explanation: '"Come under fire" = be criticised / attacked.',
    tags: ['vocab', 'ielts', 'c1', 'idioms'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The findings CONTRAVENE the prevailing theory.',
    options: ['support', 'contradict', 'confirm', 'extend'], answerIdx: 1,
    explanation: '"Contravene" = act against / contradict.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The report offers a PRESCIENT warning about future risks.',
    options: ['late', 'vague', 'foresighted', 'irrelevant'], answerIdx: 2,
    explanation: '"Prescient" = able to foresee / foresighted.',
    tags: ['vocab', 'ielts', 'c1'],
  },

  // GRAMMAR — modals more
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'The patient ___ have died if the paramedics had not arrived in time.',
    options: ['might', 'should', 'would', 'could'], answerIdx: 2,
    explanation: '"Would have + pp" in the main clause of a third conditional.',
    tags: ['grammar', 'modals', 'conditionals', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'You ___ have warned me about the road closure.',
    options: ['might', 'must', 'should', 'need'], answerIdx: 2,
    explanation: '"Should have + pp" = past criticism (you ought to have but didn\'t).',
    tags: ['grammar', 'modals', 'c1'],
  },

  // PHONOLOGY / stress — C1 hard
  { topic: 'phonology-stress', level: 'C1', difficulty: 'hard',
    prompt: 'In which word does the stress fall on the SECOND syllable?',
    options: ['PHOtograph', 'phoTOGraphic', 'phoTOgrapher', 'photoGRAPHic'], answerIdx: 2,
    explanation: 'Photo- prefix is unstressed; the root carries the stress. "phoTOgrapher".',
    tags: ['vocab', 'phonology', 'c1'],
  },
  { topic: 'phonology-stress', level: 'C1', difficulty: 'hard',
    prompt: 'In which word does the stress fall on the THIRD syllable?',
    options: ['eCONomic', 'economICAL', 'econoMICS', 'eCONomist'], answerIdx: 1,
    explanation: 'Suffix "-ical" is stressed: "economICAL".',
    tags: ['vocab', 'phonology', 'c1'],
  },

  // ═══════════════════════ EXTRA · A2/B1 to balance early levels ═══════════════════════
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'They ___ football every weekend.',
    options: ['plays', 'play', 'are playing', 'played'], answerIdx: 1,
    explanation: 'Plural subject takes base form: "they play".',
    tags: ['grammar', 'tenses', 'present-simple'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'I ___ to the cinema last night.',
    options: ['go', 'went', 'have gone', 'am going'], answerIdx: 1,
    explanation: 'Past simple for a finished past action with a finished-time adverbial.',
    tags: ['grammar', 'tenses', 'past-simple'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'She is ___ a book right now.',
    options: ['reads', 'read', 'reading', 'to read'], answerIdx: 2,
    explanation: 'Present continuous: action in progress now.',
    tags: ['grammar', 'tenses', 'present-continuous'],
  },
  { topic: 'tenses', level: 'B1', difficulty: 'easy',
    prompt: 'I ___ this film before. We can skip it.',
    options: ['saw', 'have seen', 'see', 'am seeing'], answerIdx: 1,
    explanation: 'Present perfect with past relevance ("we can skip").',
    tags: ['grammar', 'tenses', 'present-perfect'],
  },
  { topic: 'tenses', level: 'B1', difficulty: 'easy',
    prompt: 'We ___ here since 2020.',
    options: ['live', 'lived', 'have lived', 'are living'], answerIdx: 2,
    explanation: 'Present perfect + "since" for an ongoing situation from a past start.',
    tags: ['grammar', 'tenses', 'present-perfect'],
  },
  { topic: 'modals', level: 'A2', difficulty: 'easy',
    prompt: 'I ___ swim. I learned when I was five.',
    options: ['can', 'must', 'may', 'should'], answerIdx: 0,
    explanation: '"Can" for ability.',
    tags: ['grammar', 'modals', 'ability'],
  },
  { topic: 'modals', level: 'B1', difficulty: 'easy',
    prompt: 'You ___ see a doctor if the pain persists.',
    options: ['must', 'should', 'ought', 'could'], answerIdx: 1,
    explanation: '"Should" for advice.',
    tags: ['grammar', 'modals', 'advice'],
  },
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: 'I have ___ dog and two cats.',
    options: ['a', 'an', 'the', '—'], answerIdx: 0,
    explanation: 'First mention → "a".',
    tags: ['grammar', 'articles', 'a2'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'My birthday is ___ March.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 0,
    explanation: '"In" for months / years.',
    tags: ['grammar', 'prepositions', 'time'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'She lives ___ Main Street.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 1,
    explanation: '"On" for streets and roads.',
    tags: ['grammar', 'prepositions', 'place'],
  },
  { topic: 'prepositions', level: 'B1', difficulty: 'easy',
    prompt: 'I am thinking ___ going to Dubai next year.',
    options: ['about', 'of', 'on', 'at'], answerIdx: 0,
    explanation: '"Think about" = consider; "think of" = recall / opinion.',
    tags: ['grammar', 'prepositions', 'b1'],
  },

  // EXTRA HARD items — extra subtlety / no easy giveaways
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'On no account ___ the password to anyone.',
    options: ['you share', 'share you', 'do you share', 'you do share'], answerIdx: 2,
    explanation: '"On no account" + inversion → "do you share".',
    tags: ['grammar', 'inversion', 'c1'],
  },
  { topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'The committee demanded that he ___ in person.',
    options: ['appear', 'appears', 'appeared', 'will appear'], answerIdx: 0,
    explanation: 'Subjunctive after "demand" → base form "appear".',
    tags: ['grammar', 'subjunctive', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'You ___ have come to the meeting, but I understand your reasons.',
    options: ['must', 'should', 'needn\'t', 'ought'], answerIdx: 2,
    explanation: '"Needn\'t have + pp" = past absence of necessity (you did NOT need to, but you did).',
    tags: ['grammar', 'modals', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'She ___ have heard the news; she looked utterly unsurprised.',
    options: ['might', 'must', 'should', 'could'], answerIdx: 1,
    explanation: '"Must have + pp" = strong logical deduction from evidence.',
    tags: ['grammar', 'modals', 'c1', 'deduction'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The committee reached a CONSENSUS after three days of deliberation.',
    options: ['agreement', 'disagreement', 'decision', 'vote'], answerIdx: 0,
    explanation: '"Consensus" = general agreement.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'His argument, while ostensibly compelling, contained several RUSE assertions.',
    options: ['genuine', 'fraudulent', 'elaborate', 'convoluted'], answerIdx: 1,
    explanation: '"Ruse" = trick / fraudulent. The word collocates with "fraudulent" meaning deceptive.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The new regulation will have far-reaching IMPLICATIONS for small businesses.',
    options: ['benefits', 'consequences', 'explanations', 'suggestions'], answerIdx: 1,
    explanation: '"Implications" = consequences (especially indirect ones).',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'The minister refused to ___ the allegations as baseless.',
    options: ['dismiss', 'cast', 'throw', 'pass'], answerIdx: 0,
    explanation: '"Dismiss" + "as" = reject as.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  { topic: 'phrasal-verbs', level: 'C1', difficulty: 'hard',
    prompt: 'His lecture went ___ the point I was trying to make.',
    options: ['over', 'by', 'across', 'against'], answerIdx: 1,
    explanation: '"Go by" = pass unnoticed. "Go over" = review.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'Her suggestion went ___ thin air; nobody acted on it.',
    options: ['over', 'into', 'by', 'under'], answerIdx: 1,
    explanation: '"Go into thin air" = vanish. "Up in / into thin air" = disappear.',
    tags: ['vocab', 'idioms', 'c1'],
  },

  // ═══════════════════════ A2 · TENSES (more basics) ═══════════════════════
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'I ___ coffee every morning.',
    options: ['drinks', 'drink', 'am drinking', 'drinking'], answerIdx: 1,
    explanation: 'First person present simple: "I drink" (no -s).',
    tags: ['grammar', 'tenses', 'present-simple', 'a2'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: '___ you go to school yesterday?',
    options: ['Do', 'Does', 'Did', 'Are'], answerIdx: 2,
    explanation: 'Past simple question: "Did + subject + bare infinitive".',
    tags: ['grammar', 'tenses', 'past-simple', 'a2'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'They ___ watching TV right now.',
    options: ['is', 'are', 'was', 'have'], answerIdx: 1,
    explanation: 'Present continuous: "they are watching" (plural subject → "are").',
    tags: ['grammar', 'tenses', 'present-continuous', 'a2'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'She ___ her keys yesterday morning.',
    options: ['loses', 'is losing', 'lost', 'has lost'], answerIdx: 2,
    explanation: 'Past simple for a finished past action with explicit past time.',
    tags: ['grammar', 'tenses', 'past-simple', 'a2'],
  },
  { topic: 'tenses', level: 'A2', difficulty: 'easy',
    prompt: 'We ___ to Spain next Friday.',
    options: ['go', 'are going', 'went', 'have gone'], answerIdx: 1,
    explanation: 'Present continuous for a fixed future arrangement ("next Friday").',
    tags: ['grammar', 'tenses', 'present-continuous-future', 'a2'],
  },

  // ═══════════════════════ A2 · ARTICLES (more basics) ═══════════════════════
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: 'She is ___ doctor.',
    options: ['a', 'an', 'the', '—'], answerIdx: 0,
    explanation: '"A" before a consonant SOUND. "Doctor" begins with /d/.',
    tags: ['grammar', 'articles', 'a2'],
  },
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: '___ sun is shining today.',
    options: ['A', 'An', 'The', '—'], answerIdx: 2,
    explanation: 'Unique referent (the sun) → "the".',
    tags: ['grammar', 'articles', 'a2'],
  },
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: 'I have ___ cat and two dogs.',
    options: ['a', 'an', 'the', '—'], answerIdx: 0,
    explanation: '"A cat" (first mention, singular countable).',
    tags: ['grammar', 'articles', 'a2'],
  },
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: '___ children must go to school.',
    options: ['A', 'The', '—', 'An'], answerIdx: 2,
    explanation: 'Zero article for a generic plural: "Children in general".',
    tags: ['grammar', 'articles', 'a2'],
  },
  { topic: 'articles', level: 'A2', difficulty: 'easy',
    prompt: 'We live in ___ United States.',
    options: ['a', 'an', 'the', '—'], answerIdx: 2,
    explanation: 'Country with a political/compound name takes "the".',
    tags: ['grammar', 'articles', 'countries', 'a2'],
  },

  // ═══════════════════════ A2 · PREPOSITIONS (more basics) ═══════════════════════
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'I was born ___ March.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 0,
    explanation: 'Months use "in".',
    tags: ['grammar', 'prepositions', 'time', 'a2'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'The meeting is ___ Monday morning.',
    options: ['in', 'on', 'at', 'by'], answerIdx: 1,
    explanation: 'Days + parts of the day use "on".',
    tags: ['grammar', 'prepositions', 'time', 'a2'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'The shop is ___ the corner.',
    options: ['in', 'on', 'at', 'to'], answerIdx: 2,
    explanation: 'Fixed phrase: "at the corner".',
    tags: ['grammar', 'prepositions', 'place', 'a2'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'She goes to work ___ bus.',
    options: ['in', 'on', 'by', 'with'], answerIdx: 2,
    explanation: 'Means of transport: "by bus / car / train".',
    tags: ['grammar', 'prepositions', 'transport', 'a2'],
  },
  { topic: 'prepositions', level: 'A2', difficulty: 'easy',
    prompt: 'The cat is ___ the table.',
    options: ['under', 'on', 'in', 'between'], answerIdx: 1,
    explanation: '"On the table" = on top of the surface.',
    tags: ['grammar', 'prepositions', 'place', 'a2'],
  },

  // ═══════════════════════ A2 · MODALS ═══════════════════════
  { topic: 'modals', level: 'A2', difficulty: 'easy',
    prompt: 'I ___ swim. I learned when I was a child.',
    options: ['can', 'must', 'should', 'may'], answerIdx: 0,
    explanation: '"Can" for ability.',
    tags: ['grammar', 'modals', 'ability', 'a2'],
  },
  { topic: 'modals', level: 'A2', difficulty: 'easy',
    prompt: 'You ___ wear a seatbelt in the car.',
    options: ['can', 'must', 'would', 'could'], answerIdx: 1,
    explanation: '"Must" for obligation / rule.',
    tags: ['grammar', 'modals', 'obligation', 'a2'],
  },
  { topic: 'modals', level: 'A2', difficulty: 'easy',
    prompt: '___ I open the window? It is hot.',
    options: ['Must', 'Should', 'May', 'Need'], answerIdx: 2,
    explanation: '"May I" for polite permission requests.',
    tags: ['grammar', 'modals', 'permission', 'a2'],
  },

  // ═══════════════════════ A2 · QUESTIONS & COMPARISON ═══════════════════════
  { topic: 'questions', level: 'A2', difficulty: 'easy',
    prompt: '___ is your favourite colour?',
    options: ['What', 'Who', 'Where', 'When'], answerIdx: 0,
    explanation: '"What" for things/ideas.',
    tags: ['grammar', 'questions', 'wh-words', 'a2'],
  },
  { topic: 'comparison', level: 'A2', difficulty: 'easy',
    prompt: 'Mount Everest is ___ than Mont Blanc.',
    options: ['tall', 'taller', 'more tall', 'most tall'], answerIdx: 1,
    explanation: 'Short adjectives: "-er" + "than" for comparative.',
    tags: ['grammar', 'comparison', 'a2'],
  },
  { topic: 'comparison', level: 'A2', difficulty: 'easy',
    prompt: 'She is ___ girl in the class.',
    options: ['tall', 'taller', 'the tallest', 'more tall'], answerIdx: 2,
    explanation: 'Superlative short adj: "the + adj-est".',
    tags: ['grammar', 'comparison', 'a2'],
  },

  // ═══════════════════════ B1 · MORE PHONOLOGY & VOCAB ═══════════════════════
  { topic: 'phonology-stress', level: 'B1', difficulty: 'easy',
    prompt: 'Which word has the stress on the FIRST syllable?',
    options: ['beGAU', 'bookBAY', 'baKE', 'edUcation'], answerIdx: 0,
    explanation: 'Most 2-syllable nouns are stressed on the first syllable (BAcon-old).',
    tags: ['pronunciation', 'stress', 'b1'],
  },
  { topic: 'phonology-stress', level: 'B1', difficulty: 'easy',
    prompt: 'Which word is stressed on the SECOND syllable?',
    options: ['apple', 'teacher', 'happy', 'table'], answerIdx: 1,
    explanation: '"teacher" = /ti-ˈCHAY- / suh; agent nouns (-er) often take stress on the second syllable.',
    tags: ['pronunciation', 'stress', 'b1'],
  },
  { topic: 'vocab-collations', level: 'B1', difficulty: 'easy',
    prompt: 'I need to ___ a decision by tomorrow.',
    options: ['do', 'make', 'take', 'have'], answerIdx: 1,
    explanation: 'Fixed collocation: "make a decision".',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-collations', level: 'B1', difficulty: 'easy',
    prompt: 'She ___ a mistake on the form.',
    options: ['did', 'made', 'took', 'had'], answerIdx: 1,
    explanation: 'Fixed collocation: "make a mistake".',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-collations', level: 'B1', difficulty: 'easy',
    prompt: 'He always ___ his homework on time.',
    options: ['makes', 'does', 'takes', 'has'], answerIdx: 1,
    explanation: 'Fixed collocation: "do homework".',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-collations', level: 'B1', difficulty: 'easy',
    prompt: 'Could you ___ me a favour?',
    options: ['give', 'do', 'make', 'take'], answerIdx: 1,
    explanation: 'Fixed collocation: "do somebody a favour".',
    tags: ['vocab', 'collocations', 'b1'],
  },

  // ═══════════════════════ B1 · MORE RELATIVES, REPORTING, COMPARISON ═══════════════════════
  { topic: 'relative-clauses', level: 'B1', difficulty: 'easy',
    prompt: 'The man ___ lives next door is a doctor.',
    options: ['who', 'which', 'whose', 'where'], answerIdx: 0,
    explanation: '"Who" for people as the subject of the relative clause.',
    tags: ['grammar', 'relative-clauses', 'b1'],
  },
  { topic: 'relative-clauses', level: 'B1', difficulty: 'easy',
    prompt: 'This is the book ___ I bought yesterday.',
    options: ['who', 'which', 'whose', 'where'], answerIdx: 1,
    explanation: '"Which" for things as the object of the relative clause.',
    tags: ['grammar', 'relative-clauses', 'b1'],
  },
  { topic: 'reporting', level: 'B1', difficulty: 'easy',
    prompt: 'He said that he ___ tired.',
    options: ['is', 'was', 'were', 'has'], answerIdx: 1,
    explanation: 'Reported speech: present → past ("is" → "was").',
    tags: ['grammar', 'reporting', 'b1'],
  },
  { topic: 'reporting', level: 'B1', difficulty: 'easy',
    prompt: 'She told me that she ___ to Paris the week before.',
    options: ['goes', 'went', 'has gone', 'had gone'], answerIdx: 3,
    explanation: 'Reported speech: past simple → past perfect ("went" → "had gone").',
    tags: ['grammar', 'reporting', 'b1'],
  },
  { topic: 'comparison', level: 'B1', difficulty: 'easy',
    prompt: 'This book is ___ interesting ___ that one.',
    options: ['as / as', 'so / as', 'more / than', 'as / than'], answerIdx: 0,
    explanation: 'Equal comparison: "as + adj + as".',
    tags: ['grammar', 'comparison', 'b1'],
  },
  { topic: 'comparison', level: 'B1', difficulty: 'easy',
    prompt: 'It is ___ hot today ___ yesterday.',
    options: ['as / as', 'so / as', 'more / than', 'too / as'], answerIdx: 0,
    explanation: 'Equal comparison (affirmative): "as + adj + as".',
    tags: ['grammar', 'comparison', 'b1'],
  },

  // ═══════════════════════ B2 · MORE LINKERS & VOCAB ═══════════════════════
  { topic: 'linkers', level: 'B2', difficulty: 'easy',
    prompt: 'He was tired ___ he kept on working.',
    options: ['but', 'because', 'although', 'so'], answerIdx: 0,
    explanation: '"But" for contrast between two clauses.',
    tags: ['grammar', 'linkers', 'b2'],
  },
  { topic: 'linkers', level: 'B2', difficulty: 'easy',
    prompt: '___ it was raining, we stayed home.',
    options: ['Because', 'Although', 'Since', 'Unless'], answerIdx: 0,
    explanation: '"Because" + clause = reason.',
    tags: ['grammar', 'linkers', 'b2'],
  },
  { topic: 'linkers', level: 'B2', difficulty: 'hard',
    prompt: 'Much ___ I respect his motives, I cannot condone his methods.',
    options: ['like', 'as', 'though', 'whereas'], answerIdx: 1,
    explanation: '"Much as" = concessive (formal). Not "although".',
    tags: ['grammar', 'linkers', 'concession', 'b2'],
  },
  { topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'The committee will ___ a final decision on Friday.',
    options: ['do', 'make', 'reach', 'have'], answerIdx: 2,
    explanation: 'Fixed collocation: "reach a decision".',
    tags: ['vocab', 'collocations', 'b2'],
  },
  { topic: 'vocab-collations', level: 'B2', difficulty: 'easy',
    prompt: 'He has a strong ___ for chocolate.',
    options: ['fondness', 'desire', 'longing', 'wish'], answerIdx: 0,
    explanation: '"Have a fondness for" = like a lot (formal).',
    tags: ['vocab', 'collocations', 'b2'],
  },
  { topic: 'vocab-collations', level: 'B2', difficulty: 'hard',
    prompt: 'His words bore no relation ___ the evidence presented in court.',
    options: ['with', 'to', 'of', 'for'], answerIdx: 1,
    explanation: 'Fixed collocation: "bear relation to" (not "with").',
    tags: ['vocab', 'collocations', 'b2'],
  },
  { topic: 'vocab-ielts', level: 'B2', difficulty: 'easy',
    prompt: 'The professor ___ an explanation for the unusual phenomenon.',
    options: ['put forward', 'put off', 'put up with', 'put in'], answerIdx: 0,
    explanation: '"Put forward" = propose / suggest.',
    tags: ['vocab', 'phrasal-verbs', 'b2'],
  },
  { topic: 'vocab-ielts', level: 'B2', difficulty: 'easy',
    prompt: 'I cannot ___ any longer with this noise.',
    options: ['put forward', 'put off', 'put up', 'put down'], answerIdx: 2,
    explanation: '"Put up with" = tolerate.',
    tags: ['vocab', 'phrasal-verbs', 'b2'],
  },

  // ═══════════════════════ B2 · MORE PASSIVES & GERUND/INFINITIVE ═══════════════════════
  { topic: 'passives', level: 'B2', difficulty: 'easy',
    prompt: 'The new bridge ___ by the end of the year.',
    options: ['will complete', 'will be completed', 'will have completed', 'is completing'], answerIdx: 1,
    explanation: 'Passive voice + future: "will be + past participle".',
    tags: ['grammar', 'passives', 'b2'],
  },
  { topic: 'passives', level: 'B2', difficulty: 'hard',
    prompt: 'The suspect is believed ___ the country before the police arrived.',
    options: ['to leave', 'to have left', 'leaving', 'left'], answerIdx: 1,
    explanation: '"Be believed to have + pp" = past perfect infinitive in passive reporting.',
    tags: ['grammar', 'passives', 'b2'],
  },
  { topic: 'gerund-infinitive', level: 'B2', difficulty: 'easy',
    prompt: 'I enjoy ___ to classical music.',
    options: ['listen', 'to listen', 'listening', 'listened'], answerIdx: 2,
    explanation: '"Enjoy" + gerund (-ing form).',
    tags: ['grammar', 'gerund-infinitive', 'b2'],
  },
  { topic: 'gerund-infinitive', level: 'B2', difficulty: 'easy',
    prompt: 'She decided ___ a new language.',
    options: ['learn', 'to learn', 'learning', 'learned'], answerIdx: 1,
    explanation: '"Decide" + full infinitive (to + bare).',
    tags: ['grammar', 'gerund-infinitive', 'b2'],
  },
  { topic: 'gerund-infinitive', level: 'B2', difficulty: 'hard',
    prompt: 'I distinctly remember ___ the door before leaving the house.',
    options: ['to lock', 'locking', 'locked', 'lock'], answerIdx: 1,
    explanation: '"Remember" + gerund = recall doing it (NOT "to lock" = future).',
    tags: ['grammar', 'gerund-infinitive', 'b2'],
  },
  { topic: 'gerund-infinitive', level: 'B2', difficulty: 'hard',
    prompt: 'He stopped ___ a coffee on his way to work.',
    options: ['to have', 'having', 'had', 'having had'], answerIdx: 0,
    explanation: '"Stop + to-inf" = pause in order to do. "Stop + -ing" = cease doing.',
    tags: ['grammar', 'gerund-infinitive', 'b2'],
  },
  { topic: 'confused-words', level: 'B2', difficulty: 'easy',
    prompt: 'I am ___ to my teacher carefully.',
    options: ['listening', 'hearing', 'sounding', 'looking'], answerIdx: 0,
    explanation: '"Listen to" = deliberate; "hear" = passive sense.',
    tags: ['vocab', 'confused-words', 'b2'],
  },
  { topic: 'confused-words', level: 'B2', difficulty: 'hard',
    prompt: 'The patient was ___ to a hospital in the capital.',
    options: ['brought', 'fetched', 'carried', 'taken'], answerIdx: 0,
    explanation: '"Take somebody to" + destination; "bring" = toward speaker; "carry" = no direction implied.',
    tags: ['vocab', 'confused-words', 'b2'],
  },
  { topic: 'word-formation', level: 'B2', difficulty: 'easy',
    prompt: 'She gave a ___ speech at the conference.',
    options: ['beauty', 'beautify', 'beautiful', 'beautifully'], answerIdx: 2,
    explanation: 'Adjective needed before noun "speech".',
    tags: ['vocab', 'word-formation', 'b2'],
  },
  { topic: 'word-formation', level: 'B2', difficulty: 'hard',
    prompt: 'His ___ of the situation impressed the board.',
    options: ['analyse', 'analyst', 'analysis', 'analytic'], answerIdx: 2,
    explanation: '"Analysis" (noun) needed after possessive "His ___ of".',
    tags: ['vocab', 'word-formation', 'b2'],
  },

  // ═══════════════════════ C1 · HARDER SUBJUNCTIVE & INVERSION ═══════════════════════
  { topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'The board demanded that he ___ his decision immediately.',
    options: ['reverses', 'reverse', 'reversed', 'is reversing'], answerIdx: 1,
    explanation: 'Subjunctive after "demand that": base form ("reverse").',
    tags: ['grammar', 'subjunctive', 'c1'],
  },
  { topic: 'subjunctive', level: 'C1', difficulty: 'hard',
    prompt: 'It is essential that every member ___ the code of conduct.',
    options: ['respects', 'respect', 'respected', 'is respecting'], answerIdx: 1,
    explanation: 'Subjunctive after "It is essential that": base form.',
    tags: ['grammar', 'subjunctive', 'c1'],
  },
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Never before ___ such a spectacular failure.',
    options: ['have we witnessed', 'we have witnessed', 'did we witnessed', 'we witnessed'], answerIdx: 0,
    explanation: 'Inversion after negative adverbials: "Never before have we witnessed".',
    tags: ['grammar', 'inversion', 'c1'],
  },
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Rarely ___ a more compelling argument.',
    options: ['I have heard', 'have I heard', 'did I heard', 'I heard'], answerIdx: 1,
    explanation: 'Inversion after "Rarely": auxiliary + subject + past participle.',
    tags: ['grammar', 'inversion', 'c1'],
  },
  { topic: 'inversion', level: 'C1', difficulty: 'hard',
    prompt: 'Not only ___ the deadline, but she also exceeded the quality bar.',
    options: ['she met', 'did she meet', 'she meets', 'does she meet'], answerIdx: 1,
    explanation: 'Inversion after "Not only": auxiliary + subject + verb.',
    tags: ['grammar', 'inversion', 'c1'],
  },

  // ═══════════════════════ C1 · HARDER MODALS & REPORTING ═══════════════════════
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'You ___ have warned me about the meeting; I would have come.',
    options: ['should', 'must', 'ought', 'might'], answerIdx: 0,
    explanation: '"Should have + pp" = past regret (you didn\'t, but you should have).',
    tags: ['grammar', 'modals', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'He ___ have stolen the money; he was with me all evening.',
    options: ['mustn\'t', 'shouldn\'t', 'can\'t', 'needn\'t'], answerIdx: 2,
    explanation: '"Can\'t have + pp" = strong past negative deduction.',
    tags: ['grammar', 'modals', 'deduction', 'c1'],
  },
  { topic: 'reporting', level: 'C1', difficulty: 'hard',
    prompt: 'He denied ___ any knowledge of the affair.',
    options: ['to have', 'having', 'had', 'have'], answerIdx: 1,
    explanation: '"Deny" + gerund (NOT infinitive): "denied having".',
    tags: ['grammar', 'reporting', 'c1'],
  },
  { topic: 'reporting', level: 'C1', difficulty: 'hard',
    prompt: 'The minister is reported ___ his resignation later today.',
    options: ['to submit', 'to have submitted', 'submitting', 'submitted'], answerIdx: 0,
    explanation: '"Be reported to + bare-inf" = present/future reported action.',
    tags: ['grammar', 'reporting', 'passive', 'c1'],
  },
  { topic: 'passives', level: 'C1', difficulty: 'hard',
    prompt: 'The proposal, ___ by the committee, was finally approved.',
    options: ['having reviewed', 'having been reviewed', 'to review', 'reviewed'], answerIdx: 1,
    explanation: '"Having been + pp" = past perfect passive participle reduced clause.',
    tags: ['grammar', 'passives', 'participles', 'c1'],
  },

  // ═══════════════════════ C1 · HARDER VOCAB & IDIOMS ═══════════════════════
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The Minister refused to ___ the allegations, calling them "baseless".',
    options: ['dismiss', 'discard', 'dispel', 'disregard'], answerIdx: 0,
    explanation: '"Dismiss + allegations" = reject formally. "Dispel" = drive away (doubts/fears).',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The committee reached a CONSENSUS after three days of deliberation.',
    options: ['agreement', 'decision', 'vote', 'verdict'], answerIdx: 0,
    explanation: '"Consensus" = general agreement among the group.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The findings have far-reaching IMPLICATIONS for public health policy.',
    options: ['benefits', 'consequences', 'suggestions', 'explanations'], answerIdx: 1,
    explanation: '"Implications" = indirect consequences (especially negative).',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'His ostensible GENUINE concern masked ulterior motives.',
    options: ['genuine', 'apparent', 'explicit', 'manifest'], answerIdx: 1,
    explanation: '"Ostensible" = apparent / seeming (NOT "ostensible genuine").',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The PRESIDENTIAL ADDRESS was delivered to a packed chamber.',
    options: ['presidential', 'president', 'preside', 'presidency'], answerIdx: 0,
    explanation: 'Adjective needed before noun → "presidential".',
    tags: ['vocab', 'word-formation', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The court found him ___ of fraud.',
    options: ['guilty', 'guilt', 'guiltily', 'guiltless'], answerIdx: 0,
    explanation: 'Fixed: "found guilty of".',
    tags: ['vocab', 'collocations', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'His theory does not ___ water; it falls apart with the slightest scrutiny.',
    options: ['hold', 'make', 'bear', 'carry'], answerIdx: 0,
    explanation: '"Hold water" = be valid / stand up to examination.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'She has a knack ___ putting people at ease.',
    options: ['for', 'of', 'at', 'in'], answerIdx: 0,
    explanation: 'Fixed collocation: "a knack for" + -ing.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'The committee threw the proposal ___ on a technicality.',
    options: ['out', 'away', 'off', 'back'], answerIdx: 0,
    explanation: '"Throw out" = reject (a motion/proposal).',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'The decision went ___ against him; the board rejected his proposal.',
    options: ['against', 'for', 'by', 'over'], answerIdx: 0,
    explanation: '"Go against" = be unfavourable to.',
    tags: ['vocab', 'phrasal-verbs', 'c1'],
  },

  // ═══════════════════════ C1 · MORE ADVANCED — FALSE COGNATES & SPELLING ═══════════════════════
  { topic: 'false-cognates', level: 'C1', difficulty: 'hard',
    prompt: 'I need to ___ a sensible decision, not an emotional one.',
    options: ['make', 'do', 'take', 'have'], answerIdx: 0,
    explanation: '"Make a decision" is the only natural collocation here.',
    tags: ['vocab', 'collocations', 'c1'],
  },
  { topic: 'false-cognates', level: 'C1', difficulty: 'hard',
    prompt: 'She gave a long and ___ explanation.',
    options: ['detailed', 'detail', 'in detail', 'details'], answerIdx: 0,
    explanation: 'Adjective needed before "explanation" → "detailed".',
    tags: ['vocab', 'collocations', 'c1'],
  },
  { topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Which is the CORRECT spelling?',
    options: ['accomodate', 'accommodate', 'acommodate', 'accomodatte'], answerIdx: 1,
    explanation: '"Accommodate" has two C\'s and two M\'s: ac-COM-mod-ate.',
    tags: ['spelling', 'c1'],
  },
  { topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Which is the CORRECT spelling?',
    options: ['embarras', 'embarrass', 'embarras', 'embarass'], answerIdx: 1,
    explanation: '"Embarrass" has two R\'s and two S\'s.',
    tags: ['spelling', 'c1'],
  },
  { topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Which is the CORRECT spelling?',
    options: ['occured', 'occurred', 'ocurred', 'occurd'], answerIdx: 1,
    explanation: 'Final syllable doubled before -ed: "occurred".',
    tags: ['spelling', 'c1'],
  },
  { topic: 'spelling', level: 'C1', difficulty: 'hard',
    prompt: 'Which is the CORRECT spelling?',
    options: ['neccessary', 'necessery', 'necessary', 'neccesary'], answerIdx: 2,
    explanation: '"Necessary" = one C, two S\'s.',
    tags: ['spelling', 'c1'],
  },
  { topic: 'phonology-stress', level: 'C1', difficulty: 'hard',
    prompt: 'Which C1 word carries primary stress on the FINAL syllable?',
    options: ['photograph', 'photographer', 'photographic', 'photography'], answerIdx: 1,
    explanation: '"pho-TOG-raph-er" — nouns of person often shift stress to the penultimate.',
    tags: ['pronunciation', 'stress', 'c1'],
  },
  { topic: 'phonology-stress', level: 'C1', difficulty: 'hard',
    prompt: 'Which word has the SAME stress pattern as "deMOgrapHIC"?',
    options: ['ECOlogical', 'bioloGYspear', 'phoTOGraphy', 'econoMICS'], answerIdx: 0,
    explanation: 'Stressed ante-penultimate: E-co-LO-gi-cal ↔ de-mo-GRA-phic.',
    tags: ['pronunciation', 'stress', 'c1'],
  },

  // ═══════════════════════ C1 · MORE ADVANCED — MIXED CONDITIONALS & MODAL PERFECTION ═══════════════════════
  { topic: 'conditionals', level: 'C1', difficulty: 'hard',
    prompt: 'If she ___ harder at school, she would have a better job now.',
    options: ['had studied', 'has studied', 'studied', 'studies'], answerIdx: 0,
    explanation: 'Mixed: past-perfect if-clause (imaginary past) + would + bare (imaginary present).',
    tags: ['grammar', 'conditionals', 'mixed', 'c1'],
  },
  { topic: 'conditionals', level: 'C1', difficulty: 'hard',
    prompt: 'Were it not for the timely intervention, the patient ___ .',
    options: ['would die', 'would have died', 'will have died', 'had died'], answerIdx: 1,
    explanation: '"Were it not for" = past hypothetical → "would have died".',
    tags: ['grammar', 'conditionals', 'third', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'You ___ better consult a lawyer before signing the contract.',
    options: ['had', 'would', 'should', 'have'], answerIdx: 0,
    explanation: '"Had better" = strong advice (past form of "had" = present meaning).',
    tags: ['grammar', 'modals', 'advice', 'c1'],
  },
  { topic: 'modals', level: 'C1', difficulty: 'hard',
    prompt: 'He ___ well have been the thief; he had opportunity and motive.',
    options: ['might', 'should', 'must', 'ought'], answerIdx: 0,
    explanation: '"Might well have + pp" = past possibility with strong likelihood.',
    tags: ['grammar', 'modals', 'c1'],
  },

  // ═══════════════════════ C1 · EXTRA HARD: SEMANTIC NUANCE ═══════════════════════
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The two reports are fundamentally ___ : one supports the policy, the other rejects it.',
    options: ['at odds', 'in common', 'in line', 'on par'], answerIdx: 0,
    explanation: '"At odds" = in conflict. "In line" = in agreement. "On par" = equal.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'After the scandal, the senator was forced to ___ his candidacy.',
    options: ['withdraw', 'retreat', 'remove', 'abandon'], answerIdx: 0,
    explanation: '"Withdraw" a candidacy = formally pull out. "Abandon" = no longer support (less formal).',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The findings were ___ : they could not be replicated in subsequent studies.',
    options: ['inconclusive', 'conclusive', 'conclusive', 'irrelevant'], answerIdx: 0,
    explanation: '"Inconclusive" = not decisive. "Irrelevant" = not pertinent.',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The court ruled that the confession had been ___ under duress.',
    options: ['coerced', 'enforced', 'urged', 'pressured'], answerIdx: 0,
    explanation: '"Coerce" = force by threat. "Enforce" = impose (a rule).',
    tags: ['vocab', 'ielts', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'Her speech was so ___ that even her opponents applauded.',
    options: ['compelling', 'compelled', 'compulsion', 'compulsory'], answerIdx: 0,
    explanation: 'Adjective form: "compelling" = persuasive (NOT "compelled" = forced).',
    tags: ['vocab', 'word-formation', 'c1'],
  },
  { topic: 'vocab-ielts', level: 'C1', difficulty: 'hard',
    prompt: 'The Minister offered a ___ apology, but refused to resign.',
    options: ['half-hearted', 'whole-hearted', 'warm-hearted', 'cold-hearted'], answerIdx: 0,
    explanation: '"Half-hearted" = insincere, lacking enthusiasm.',
    tags: ['vocab', 'collocations', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'He is the kind of person who always ___ the line.',
    options: ['toes', 'tips', 'steps', 'treads'], answerIdx: 0,
    explanation: '"Toe the line" = conform to expectations.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'After months of negotiations, the parties finally saw ___ to ___ .',
    options: ['eye / eye', 'face / face', 'hand / hand', 'heart / heart'], answerIdx: 0,
    explanation: '"See eye to eye" = agree on something.',
    tags: ['vocab', 'idioms', 'c1'],
  },
  { topic: 'idioms', level: 'C1', difficulty: 'hard',
    prompt: 'The professor did not ___ any favours when grading the exams.',
    options: ['pull', 'make', 'do', 'take'], answerIdx: 0,
    explanation: '"Pull favours" = use influence to give unfair advantage.',
    tags: ['vocab', 'idioms', 'c1'],
  },

  // ═══════════════════════ B2 · EXTRA HARD: NUANCE & SUBTLE COLLOCATIONS ═══════════════════════
  { topic: 'vocab-collations', level: 'B2', difficulty: 'hard',
    prompt: 'The new policy will have ___ consequences for small businesses.',
    options: ['far-reaching', 'far-going', 'far-extending', 'far-lasting'], answerIdx: 0,
    explanation: 'Only "far-reaching" is an established collocation.',
    tags: ['vocab', 'collocations', 'b2'],
  },
  { topic: 'vocab-collations', level: 'B2', difficulty: 'hard',
    prompt: 'She has a ___ for languages; she speaks five fluently.',
    options: ['flair', 'flame', 'flare', 'flash'], answerIdx: 0,
    explanation: '"Have a flair for" = natural talent. "Flare" = signal/argument.',
    tags: ['vocab', 'collocations', 'b2'],
  },
  { topic: 'phrasal-verbs', level: 'B2', difficulty: 'hard',
    prompt: 'I cannot ___ any longer with this noise; please stop.',
    options: ['put up', 'put off', 'put away', 'put down'], answerIdx: 0,
    explanation: '"Put up with" = tolerate. The others do not collocate with "any longer" + noise.',
    tags: ['phrasal-verbs', 'b2'],
  },
  { topic: 'phrasal-verbs', level: 'B2', difficulty: 'hard',
    prompt: 'The minister refused to ___ the allegations as baseless.',
    options: ['dismiss', 'cast', 'throw', 'pass'], answerIdx: 0,
    explanation: '"Dismiss + allegations" = formally reject. "Cast" + "doubt on" but not "as".',
    tags: ['phrasal-verbs', 'b2'],
  },
  { topic: 'phrasal-verbs', level: 'B2', difficulty: 'hard',
    prompt: 'His lecture went ___ the point I was trying to make.',
    options: ['over', 'by', 'across', 'against'], answerIdx: 1,
    explanation: '"Go by + point" = pass without notice. "Go over" = review.',
    tags: ['phrasal-verbs', 'b2'],
  },
  { topic: 'confused-words', level: 'B2', difficulty: 'hard',
    prompt: 'She is very ___ of her family\'s traditions.',
    options: ['conscious', 'conscience', 'consciousness', 'conscientious'], answerIdx: 0,
    explanation: '"Be conscious of" = aware of. "Conscientious" = thorough. "Conscience" = moral sense.',
    tags: ['vocab', 'confused-words', 'b2'],
  },
  { topic: 'confused-words', level: 'B2', difficulty: 'hard',
    prompt: 'The suspect made a full ___ .',
    options: ['confession', 'profession', 'session', 'mission'], answerIdx: 0,
    explanation: '"Confession" = admission of guilt. "Profession" = declaration of belief/occupation.',
    tags: ['vocab', 'confused-words', 'b2'],
  },
  { topic: 'vocab-ielts', level: 'B2', difficulty: 'hard',
    prompt: 'His ___ explanation left us more confused than before.',
    options: ['confused', 'confusing', 'confusion', 'confuse'], answerIdx: 1,
    explanation: '"Confusing" (present participle as adj) = causing confusion. "Confused" = feeling it.',
    tags: ['vocab', 'word-formation', 'b2'],
  },
  { topic: 'word-formation', level: 'B2', difficulty: 'hard',
    prompt: 'Her ___ of the new policy surprised the board.',
    options: ['critic', 'critical', 'criticise', 'criticism'], answerIdx: 3,
    explanation: 'Noun needed after "Her ___ of" → "criticism".',
    tags: ['vocab', 'word-formation', 'b2'],
  },
  { topic: 'word-formation', level: 'B2', difficulty: 'hard',
    prompt: 'He is widely ___ as the leading expert in his field.',
    options: ['acknowledge', 'acknowledged', 'acknowledging', 'acknowledgement'], answerIdx: 1,
    explanation: 'Past participle as adjective after "is" → "is widely acknowledged".',
    tags: ['vocab', 'word-formation', 'b2'],
  },

  // ═══════════════════════ B1 · MORE EASY VOCAB FOR BROAD COVERAGE ═══════════════════════
  { topic: 'vocab-ielts', level: 'B1', difficulty: 'easy',
    prompt: 'He finally ___ his dream of climbing Everest.',
    options: ['achieved', 'made', 'did', 'reached'], answerIdx: 0,
    explanation: '"Achieve" + abstract noun (dream, goal).',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-ielts', level: 'B1', difficulty: 'easy',
    prompt: 'I ___ a lot of weight last year.',
    options: ['gained', 'won', 'earned', 'got'], answerIdx: 0,
    explanation: '"Gain weight" = become heavier. "Earn" + money.',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-ielts', level: 'B1', difficulty: 'easy',
    prompt: 'The doctor told him to ___ more exercise.',
    options: ['make', 'do', 'take', 'have'], answerIdx: 2,
    explanation: '"Take exercise" = do physical activity (formal).',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'vocab-ielts', level: 'B1', difficulty: 'easy',
    prompt: 'You should ___ a break; you look tired.',
    options: ['make', 'take', 'do', 'have'], answerIdx: 1,
    explanation: '"Take a break" = rest briefly.',
    tags: ['vocab', 'collocations', 'b1'],
  },
  { topic: 'spelling', level: 'B1', difficulty: 'easy',
    prompt: 'Which is the CORRECT spelling?',
    options: ['recieve', 'receive', 'receeve', 'receeve'], answerIdx: 1,
    explanation: 'I before E except after C: "receive".',
    tags: ['spelling', 'b1'],
  },
  { topic: 'spelling', level: 'B1', difficulty: 'easy',
    prompt: 'Which is the CORRECT spelling?',
    options: ['beleive', 'believe', 'belieive', 'beleive'], answerIdx: 1,
    explanation: 'I before E in "believe" (silent "e" exception).',
    tags: ['spelling', 'b1'],
  },
  { topic: 'questions', level: 'B1', difficulty: 'easy',
    prompt: '___ did you last see her?',
    options: ['When', 'Where', 'Why', 'How'], answerIdx: 0,
    explanation: '"When" for time questions.',
    tags: ['grammar', 'questions', 'wh-words', 'b1'],
  },
  { topic: 'questions', level: 'B1', difficulty: 'easy',
    prompt: '___ is the capital of France?',
    options: ['What', 'Who', 'Where', 'When'], answerIdx: 0,
    explanation: '"What" for "which thing" (the city name).',
    tags: ['grammar', 'questions', 'wh-words', 'b1'],
  },
];